on:
  push:
    branches:
      - master
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled]
name: ci
permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6
        name: Install pnpm

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Tests & Lint & Build
        run: |
          pnpm run test
          pnpm run lint
          pnpm run build
